services:
  postgres:
    container_name: postgres
    image: postgres:17.6
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=example
    volumes:
      - pgdata:/var/lib/postgresql/data

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.3.3
    entrypoint: /opt/keycloak/bin/kc.sh start-dev --import-realm
    volumes:
      - ./Keycloak/keycloak.conf:/opt/keycloak/conf/keycloak.conf
      - ./Keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  pgdata:
